import Head from "next/head";
import Header from "../src/components/Header";
import Post from "../src/components/Post";
import User from "../src/components/User";
import styles from "../styles/Home.module.css";

export interface PostType {
  userId: number;
  id: number;
  title: string;
  body: string;
}

interface PostsType {
  posts: PostType[];
}

const baseUrl = "https://jsonplaceholder.typicode.com";

export const getStaticProps = async () => {
  const res = await fetch(`${baseUrl}/posts`);
  const data = await res.json();
  return {
    props: { posts: data },
  };
};

const Home = ({ posts }: PostsType) => {
  const sortedPosts = posts.sort((a, b) => b.userId - a.userId);

  return (
    <div>
      <Head>
        <title>test blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <User />
        {sortedPosts?.map((post) => {
          return (
            <Post
              key={post.id}
              postTitle={post.title}
              description={post.body}
              publishDate={post.userId}
              readTime={post.id}
              to="#"
            />
          );
        })}
      </main>
    </div>
  );
};

export default Home;
