/* eslint-disable react/no-unknown-property */
import type { NextPage } from "next";
import Head from "next/head";
import Header from "../src/components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>test blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        {/* user */}
        {/* posts */}
      </main>
    </div>
  );
};

export default Home;
